# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_model_parameter(object):
    def setupUi(self, model_parameter):
        model_parameter.setObjectName("model_parameter")
        model_parameter.resize(220, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(model_parameter.sizePolicy().hasHeightForWidth())
        model_parameter.setSizePolicy(sizePolicy)
        model_parameter.setMinimumSize(QtCore.QSize(220, 0))
        model_parameter.setMaximumSize(QtCore.QSize(220, 16777215))
        model_parameter.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(model_parameter)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.parameter_item = QtWidgets.QHBoxLayout()
        self.parameter_item.setObjectName("parameter_item")
        self.name = QtWidgets.QLabel(model_parameter)
        self.name.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name.setLineWidth(2)
        self.name.setWordWrap(True)
        self.name.setObjectName("name")
        self.parameter_item.addWidget(self.name)
        self.value_input = QtWidgets.QDoubleSpinBox(model_parameter)
        self.value_input.setMinimumSize(QtCore.QSize(0, 20))
        self.value_input.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.value_input.setFont(font)
        self.value_input.setStyleSheet("QDoubleSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.value_input.setObjectName("value_input")
        self.parameter_item.addWidget(self.value_input)
        self.parameter_item.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.parameter_item)

        self.retranslateUi(model_parameter)
        QtCore.QMetaObject.connectSlotsByName(model_parameter)

    def retranslateUi(self, model_parameter):
        _translate = QtCore.QCoreApplication.translate
        model_parameter.setWindowTitle(_translate("model_parameter", "Form"))
        self.name.setText(_translate("model_parameter", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    model_parameter = QtWidgets.QWidget()
    ui = Ui_model_parameter()
    ui.setupUi(model_parameter)
    model_parameter.show()
    sys.exit(app.exec_())
