# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.menu = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.menu.setFont(font)
        self.menu.setStyleSheet("QTabBar::tab {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(84, 84, 84);\n"
"}")
        self.menu.setTabPosition(QtWidgets.QTabWidget.South)
        self.menu.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.menu.setIconSize(QtCore.QSize(50, 50))
        self.menu.setElideMode(QtCore.Qt.ElideMiddle)
        self.menu.setMovable(False)
        self.menu.setObjectName("menu")
        self.prediction = QtWidgets.QWidget()
        self.prediction.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}")
        self.prediction.setObjectName("prediction")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.prediction)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.prediction)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.prediction_log = QtWidgets.QPlainTextEdit(self.prediction)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.prediction_log.setFont(font)
        self.prediction_log.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.prediction_log.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(42, 42, 42);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:  rgb(90, 90, 90);\n"
"    color: rgb(130, 130, 130);\n"
"    min-height: 30px;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(130, 130, 130);\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(130, 130, 130);\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.prediction_log.setObjectName("prediction_log")
        self.verticalLayout_3.addWidget(self.prediction_log)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.predict_image = QtWidgets.QLabel(self.prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_image.sizePolicy().hasHeightForWidth())
        self.predict_image.setSizePolicy(sizePolicy)
        self.predict_image.setMinimumSize(QtCore.QSize(256, 256))
        self.predict_image.setMaximumSize(QtCore.QSize(256, 256))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.predict_image.setFont(font)
        self.predict_image.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.predict_image.setText("")
        self.predict_image.setObjectName("predict_image")
        self.verticalLayout_9.addWidget(self.predict_image)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.predict_results = QtWidgets.QLabel(self.prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.predict_results.sizePolicy().hasHeightForWidth())
        self.predict_results.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.predict_results.setFont(font)
        self.predict_results.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.predict_results.setText("")
        self.predict_results.setWordWrap(True)
        self.predict_results.setObjectName("predict_results")
        self.horizontalLayout_7.addWidget(self.predict_results)
        self.predict_correct_image = QtWidgets.QLabel(self.prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.predict_correct_image.sizePolicy().hasHeightForWidth())
        self.predict_correct_image.setSizePolicy(sizePolicy)
        self.predict_correct_image.setMinimumSize(QtCore.QSize(32, 32))
        self.predict_correct_image.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.predict_correct_image.setFont(font)
        self.predict_correct_image.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.predict_correct_image.setText("")
        self.predict_correct_image.setObjectName("predict_correct_image")
        self.horizontalLayout_7.addWidget(self.predict_correct_image)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.fit_before_prediction_label = QtWidgets.QLabel(self.prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_before_prediction_label.sizePolicy().hasHeightForWidth())
        self.fit_before_prediction_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        self.fit_before_prediction_label.setFont(font)
        self.fit_before_prediction_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.fit_before_prediction_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fit_before_prediction_label.setObjectName("fit_before_prediction_label")
        self.horizontalLayout_2.addWidget(self.fit_before_prediction_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.prediction)
        self.label_9.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.prediction_batch_size_spin_box = QtWidgets.QSpinBox(self.prediction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prediction_batch_size_spin_box.sizePolicy().hasHeightForWidth())
        self.prediction_batch_size_spin_box.setSizePolicy(sizePolicy)
        self.prediction_batch_size_spin_box.setMinimumSize(QtCore.QSize(0, 25))
        self.prediction_batch_size_spin_box.setMaximumSize(QtCore.QSize(256, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.prediction_batch_size_spin_box.setFont(font)
        self.prediction_batch_size_spin_box.setStyleSheet("QSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.prediction_batch_size_spin_box.setMinimum(1)
        self.prediction_batch_size_spin_box.setMaximum(1000)
        self.prediction_batch_size_spin_box.setObjectName("prediction_batch_size_spin_box")
        self.gridLayout_3.addWidget(self.prediction_batch_size_spin_box, 1, 0, 1, 1)
        self.predict_button = QtWidgets.QPushButton(self.prediction)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.predict_button.setFont(font)
        self.predict_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.predict_button.setObjectName("predict_button")
        self.gridLayout_3.addWidget(self.predict_button, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.menu.addTab(self.prediction, "")
        self.fitting = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitting.sizePolicy().hasHeightForWidth())
        self.fitting.setSizePolicy(sizePolicy)
        self.fitting.setObjectName("fitting")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fitting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.fitting_log = QtWidgets.QPlainTextEdit(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.fitting_log.setFont(font)
        self.fitting_log.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.fitting_log.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(42, 42, 42);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color:  rgb(90, 90, 90);\n"
"    color: rgb(130, 130, 130);\n"
"    min-height: 30px;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(130, 130, 130);\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(130, 130, 130);\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(185, 0, 92);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.fitting_log.setObjectName("fitting_log")
        self.verticalLayout_4.addWidget(self.fitting_log)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.optimizer_combo_box = QtWidgets.QComboBox(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.optimizer_combo_box.setFont(font)
        self.optimizer_combo_box.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.optimizer_combo_box.setObjectName("optimizer_combo_box")
        self.optimizer_combo_box.addItem("")
        self.optimizer_combo_box.addItem("")
        self.optimizer_combo_box.addItem("")
        self.gridLayout.addWidget(self.optimizer_combo_box, 1, 0, 1, 1)
        self.train_dataset_size_spin_box = QtWidgets.QSpinBox(self.fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.train_dataset_size_spin_box.sizePolicy().hasHeightForWidth())
        self.train_dataset_size_spin_box.setSizePolicy(sizePolicy)
        self.train_dataset_size_spin_box.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.train_dataset_size_spin_box.setFont(font)
        self.train_dataset_size_spin_box.setStyleSheet("QSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.train_dataset_size_spin_box.setMinimum(1)
        self.train_dataset_size_spin_box.setMaximum(5000)
        self.train_dataset_size_spin_box.setObjectName("train_dataset_size_spin_box")
        self.gridLayout.addWidget(self.train_dataset_size_spin_box, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.fitting_button = QtWidgets.QPushButton(self.fitting)
        self.fitting_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.fitting_button.setFont(font)
        self.fitting_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.fitting_button.setObjectName("fitting_button")
        self.gridLayout.addWidget(self.fitting_button, 1, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.epoch_count_spin_box = QtWidgets.QSpinBox(self.fitting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch_count_spin_box.sizePolicy().hasHeightForWidth())
        self.epoch_count_spin_box.setSizePolicy(sizePolicy)
        self.epoch_count_spin_box.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.epoch_count_spin_box.setFont(font)
        self.epoch_count_spin_box.setStyleSheet("QSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.epoch_count_spin_box.setMinimum(1)
        self.epoch_count_spin_box.setMaximum(10000)
        self.epoch_count_spin_box.setObjectName("epoch_count_spin_box")
        self.gridLayout.addWidget(self.epoch_count_spin_box, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.fitting)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.delete_model_button = QtWidgets.QPushButton(self.fitting)
        self.delete_model_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.delete_model_button.setFont(font)
        self.delete_model_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.delete_model_button.setObjectName("delete_model_button")
        self.gridLayout.addWidget(self.delete_model_button, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.menu.addTab(self.fitting, "")
        self.build = QtWidgets.QWidget()
        self.build.setObjectName("build")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.build)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model_layout = QtWidgets.QWidget(self.build)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_layout.sizePolicy().hasHeightForWidth())
        self.model_layout.setSizePolicy(sizePolicy)
        self.model_layout.setMinimumSize(QtCore.QSize(200, 0))
        self.model_layout.setObjectName("model_layout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.model_layout)
        self.verticalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.model_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.layer_item_2 = QtWidgets.QHBoxLayout()
        self.layer_item_2.setObjectName("layer_item_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.layer_item_2.addLayout(self.horizontalLayout_8)
        self.name_2 = QtWidgets.QLabel(self.model_layout)
        self.name_2.setMinimumSize(QtCore.QSize(200, 30))
        self.name_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.name_2.setFont(font)
        self.name_2.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name_2.setObjectName("name_2")
        self.layer_item_2.addWidget(self.name_2)
        self.parameters_layout_3 = QtWidgets.QHBoxLayout()
        self.parameters_layout_3.setObjectName("parameters_layout_3")
        self.parameter_item = QtWidgets.QHBoxLayout()
        self.parameter_item.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.parameter_item.setObjectName("parameter_item")
        self.name_5 = QtWidgets.QLabel(self.model_layout)
        self.name_5.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_5.setFont(font)
        self.name_5.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name_5.setLineWidth(2)
        self.name_5.setWordWrap(True)
        self.name_5.setObjectName("name_5")
        self.parameter_item.addWidget(self.name_5)
        self.image_scale_spin_box = QtWidgets.QDoubleSpinBox(self.model_layout)
        self.image_scale_spin_box.setEnabled(True)
        self.image_scale_spin_box.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.image_scale_spin_box.setFont(font)
        self.image_scale_spin_box.setStyleSheet("QDoubleSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.image_scale_spin_box.setDecimals(0)
        self.image_scale_spin_box.setMinimum(8.0)
        self.image_scale_spin_box.setMaximum(512.0)
        self.image_scale_spin_box.setObjectName("image_scale_spin_box")
        self.parameter_item.addWidget(self.image_scale_spin_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameter_item.addItem(spacerItem)
        self.parameter_item.setStretch(0, 4)
        self.parameter_item.setStretch(1, 1)
        self.parameters_layout_3.addLayout(self.parameter_item)
        self.layer_item_2.addLayout(self.parameters_layout_3)
        self.layer_item_2.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.layer_item_2)
        self.scrollArea = QtWidgets.QScrollArea(self.model_layout)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.model_layers_layout = QtWidgets.QWidget()
        self.model_layers_layout.setGeometry(QtCore.QRect(0, 0, 785, 489))
        self.model_layers_layout.setObjectName("model_layers_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.model_layers_layout)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.scrollArea.setWidget(self.model_layers_layout)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.layer_item_4 = QtWidgets.QHBoxLayout()
        self.layer_item_4.setObjectName("layer_item_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.layer_item_4.addLayout(self.horizontalLayout_10)
        self.name_4 = QtWidgets.QLabel(self.model_layout)
        self.name_4.setMinimumSize(QtCore.QSize(200, 30))
        self.name_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.name_4.setFont(font)
        self.name_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name_4.setObjectName("name_4")
        self.layer_item_4.addWidget(self.name_4)
        self.parameters_layout_5 = QtWidgets.QHBoxLayout()
        self.parameters_layout_5.setObjectName("parameters_layout_5")
        self.parameter_item_3 = QtWidgets.QHBoxLayout()
        self.parameter_item_3.setObjectName("parameter_item_3")
        self.name_7 = QtWidgets.QLabel(self.model_layout)
        self.name_7.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_7.setFont(font)
        self.name_7.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name_7.setLineWidth(2)
        self.name_7.setWordWrap(True)
        self.name_7.setObjectName("name_7")
        self.parameter_item_3.addWidget(self.name_7)
        self.output_neuron_count = QtWidgets.QDoubleSpinBox(self.model_layout)
        self.output_neuron_count.setEnabled(False)
        self.output_neuron_count.setMinimumSize(QtCore.QSize(0, 0))
        self.output_neuron_count.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.output_neuron_count.setFont(font)
        self.output_neuron_count.setStyleSheet("QDoubleSpinBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView {\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QDoubleSpinBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.output_neuron_count.setDecimals(0)
        self.output_neuron_count.setMinimum(2.0)
        self.output_neuron_count.setObjectName("output_neuron_count")
        self.parameter_item_3.addWidget(self.output_neuron_count)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameter_item_3.addItem(spacerItem2)
        self.parameter_item_3.setStretch(0, 1)
        self.parameters_layout_5.addLayout(self.parameter_item_3)
        self.layer_item_4.addLayout(self.parameters_layout_5)
        self.layer_item_4.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.layer_item_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_model_button = QtWidgets.QPushButton(self.model_layout)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.change_model_button.setFont(font)
        self.change_model_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.change_model_button.setObjectName("change_model_button")
        self.horizontalLayout_4.addWidget(self.change_model_button)
        self.add_layer_button = QtWidgets.QPushButton(self.model_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_layer_button.sizePolicy().hasHeightForWidth())
        self.add_layer_button.setSizePolicy(sizePolicy)
        self.add_layer_button.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_layer_button.setFont(font)
        self.add_layer_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.add_layer_button.setObjectName("add_layer_button")
        self.horizontalLayout_4.addWidget(self.add_layer_button)
        self.save_model_button = QtWidgets.QPushButton(self.model_layout)
        self.save_model_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.save_model_button.setFont(font)
        self.save_model_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.save_model_button.setObjectName("save_model_button")
        self.horizontalLayout_4.addWidget(self.save_model_button)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addWidget(self.model_layout)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.menu.addTab(self.build, "")
        self.gridLayout_2.addWidget(self.menu, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_5.addWidget(self.exit_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Prediction log"))
        self.prediction_log.setPlainText(_translate("MainWindow", "Text text text"))
        self.fit_before_prediction_label.setText(_translate("MainWindow", "Fit before prediction!"))
        self.label_9.setText(_translate("MainWindow", "Prediction batch size"))
        self.predict_button.setText(_translate("MainWindow", "Predict"))
        self.menu.setTabText(self.menu.indexOf(self.prediction), _translate("MainWindow", "Prediction"))
        self.label.setText(_translate("MainWindow", "Fitting log"))
        self.fitting_log.setPlainText(_translate("MainWindow", "Text text text"))
        self.optimizer_combo_box.setItemText(0, _translate("MainWindow", "New Item"))
        self.optimizer_combo_box.setItemText(1, _translate("MainWindow", "New Item"))
        self.optimizer_combo_box.setItemText(2, _translate("MainWindow", "New Item"))
        self.label_6.setText(_translate("MainWindow", "Optimizer"))
        self.fitting_button.setText(_translate("MainWindow", "Fit!"))
        self.label_8.setText(_translate("MainWindow", "Train dataset size (each)"))
        self.label_7.setText(_translate("MainWindow", "Epoch count"))
        self.delete_model_button.setText(_translate("MainWindow", "Delete model"))
        self.menu.setTabText(self.menu.indexOf(self.fitting), _translate("MainWindow", "Fitting"))
        self.label_3.setText(_translate("MainWindow", "Model"))
        self.name_2.setText(_translate("MainWindow", "Input layer"))
        self.name_5.setText(_translate("MainWindow", "Image scale in px*px"))
        self.name_4.setText(_translate("MainWindow", "Output dense layer (softmax)"))
        self.name_7.setText(_translate("MainWindow", "Neuron count"))
        self.change_model_button.setText(_translate("MainWindow", "Change model"))
        self.add_layer_button.setText(_translate("MainWindow", "Add layer +"))
        self.save_model_button.setText(_translate("MainWindow", "Save model"))
        self.menu.setTabText(self.menu.indexOf(self.build), _translate("MainWindow", "Model Build"))
        self.exit_button.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
