# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_layer(object):
    def setupUi(self, layer):
        layer.setObjectName("layer")
        layer.resize(793, 48)
        layer.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(layer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalWidget_2 = QtWidgets.QWidget(layer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.layer_item = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.layer_item.setContentsMargins(0, 0, 0, 0)
        self.layer_item.setObjectName("layer_item")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.move_up_button = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.move_up_button.setMaximumSize(QtCore.QSize(30, 30))
        self.move_up_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.move_up_button.setObjectName("move_up_button")
        self.horizontalLayout_4.addWidget(self.move_up_button)
        self.move_down_button = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.move_down_button.setMaximumSize(QtCore.QSize(30, 30))
        self.move_down_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.move_down_button.setObjectName("move_down_button")
        self.horizontalLayout_4.addWidget(self.move_down_button)
        self.layer_item.addLayout(self.horizontalLayout_4)
        self.name = QtWidgets.QLabel(self.horizontalWidget_2)
        self.name.setMinimumSize(QtCore.QSize(200, 30))
        self.name.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.name.setObjectName("name")
        self.layer_item.addWidget(self.name)
        self.parameters = QtWidgets.QWidget(self.horizontalWidget_2)
        self.parameters.setMinimumSize(QtCore.QSize(450, 0))
        self.parameters.setObjectName("parameters")
        self.parameters_layout_2 = QtWidgets.QHBoxLayout(self.parameters)
        self.parameters_layout_2.setObjectName("parameters_layout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameters_layout_2.addItem(spacerItem)
        self.layer_item.addWidget(self.parameters)
        self.delete_button = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.delete_button.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.delete_button.setFont(font)
        self.delete_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.delete_button.setObjectName("delete_button")
        self.layer_item.addWidget(self.delete_button)
        self.horizontalLayout_2.addWidget(self.horizontalWidget_2)

        self.retranslateUi(layer)
        QtCore.QMetaObject.connectSlotsByName(layer)

    def retranslateUi(self, layer):
        _translate = QtCore.QCoreApplication.translate
        layer.setWindowTitle(_translate("layer", "Form"))
        self.move_up_button.setText(_translate("layer", "▲"))
        self.move_down_button.setText(_translate("layer", "▼"))
        self.name.setText(_translate("layer", "TextLabel"))
        self.delete_button.setText(_translate("layer", "X"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    layer = QtWidgets.QWidget()
    ui = Ui_layer()
    ui.setupUi(layer)
    layer.show()
    sys.exit(app.exec_())
