# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layer_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_select_layer(object):
    def setupUi(self, select_layer):
        select_layer.setObjectName("select_layer")
        select_layer.resize(318, 139)
        select_layer.setMinimumSize(QtCore.QSize(300, 0))
        select_layer.setMaximumSize(QtCore.QSize(318, 16777215))
        select_layer.setStyleSheet("QDialog {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(select_layer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalWidget = QtWidgets.QWidget(select_layer)
        self.verticalWidget.setMinimumSize(QtCore.QSize(300, 120))
        self.verticalWidget.setMaximumSize(QtCore.QSize(300, 120))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.layer_select = QtWidgets.QComboBox(self.verticalWidget)
        self.layer_select.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.layer_select.setFont(font)
        self.layer_select.setStyleSheet("QComboBox {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"     color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.layer_select.setObjectName("layer_select")
        self.verticalLayout.addWidget(self.layer_select)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.select_layer_button = QtWidgets.QPushButton(self.verticalWidget)
        self.select_layer_button.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_layer_button.setFont(font)
        self.select_layer_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(124, 124, 124);\n"
"    background-color: rgb(75, 75, 75);\n"
"}")
        self.select_layer_button.setObjectName("select_layer_button")
        self.verticalLayout.addWidget(self.select_layer_button)
        self.verticalLayout_2.addWidget(self.verticalWidget)

        self.retranslateUi(select_layer)
        QtCore.QMetaObject.connectSlotsByName(select_layer)

    def retranslateUi(self, select_layer):
        _translate = QtCore.QCoreApplication.translate
        select_layer.setWindowTitle(_translate("select_layer", "Dialog"))
        self.label.setText(_translate("select_layer", "Choose layer to add:"))
        self.select_layer_button.setText(_translate("select_layer", "Select this layer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    select_layer = QtWidgets.QDialog()
    ui = Ui_select_layer()
    ui.setupUi(select_layer)
    select_layer.show()
    sys.exit(app.exec_())
